[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = 0
hook_add = 'source ~/.mydot/nvim/rc/coc.nvim.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_i = 1
hook_add = 'source ~/.mydot/nvim/rc/denite.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
on_i = 1
hook_add = 'source ~/.mydot/nvim/rc/indentLine.vim'

[[plugins]]
repo = 'itchyny/landscape.vim'
on_i = 1
hook_add = 'source ~/.mydot/nvim/rc/landscape.vim'

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'source ~/.mydot/nvim/rc/nerdtree.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_i = 1
hook_add = 'source ~/.mydot/nvim/rc/neosnippet.vim'

[[plugins]]
repo = 'kassio/neoterm'
on_i = 1
hook_add = 'source ~/.mydot/nvim/rc/neoterm.vim'

[[plugins]]
repo = 'majutsushi/tagbar'
on_i = 1
hook_add = 'source ~/.mydot/nvim/rc/tagbar.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = 'source ~/.mydot/nvim/rc/airline.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'
hook_add = 'source ~/.mydot/nvim/rc/easymotion.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'
on_i = 1

[[plugins]]
repo = 'airblade/vim-gitgutter'
on_i = 1
hook_add = 'source ~/.mydot/nvim/rc/vim-gitgutter.vim'

[[plugins]]
repo = 'osyo-manga/vim-over'
hook_add = 'source ~/.mydot/nvim/rc/vim-over.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
on_i = 1

[[plugins]]
repo = 'thinca/vim-quickrun'
on_ft = 'python'
hook_add = 'source ~/.mydot/nvim/rc/quickrun.vim'

[[plugins]]
repo = 'lambdalisue/vim-quickrun-neovim-job'




[[plugins]]
repo = 'Shougo/defx.nvim'
# depends = ['defx-icons', 'defx-git']
hook_add = 'source ~/.mydot/nvim/rc/defx.vim'

# [[plugins]]
# repo ='kristijanhusak/defx-icons'
# 
# [[plugins]]
# repo ='kristijanhusak/defx-git'
# hook_add = 'source ~/.mydot/nvim/rc/defx-git.vim'




# [[plugins]]
# repo = 'julienr/vim-cellmode'
# on_i = 1

# [[plugins]]
# repo = 'tpope/vim-dispatch'
# 
# [[plugins]]
# repo = 'janko-m/vim-test'
# depends = ['vim-dispatch']
# # let g:test#strategy = 'dispatch'
# hook_add = '''
# let g:test#strategy = {
#   \ 'nearest': 'neovim',
#   \ 'file':    'dispatch',
#   \ 'suite':   'basic',
# \}
# '''
# 
# [[plugins]]
# repo = 'aliev/vim-compiler-python'





# [[plugins]]
# repo = 'vim-scripts/vim-auto-save'
# hook_add = 'source ~/.mydot/nvim/rc/vim-auto-save.vim'





# [[plugins]]
# repo = 'Shougo/deol.nvim'
# on_i = 1
# hook_add = 'source ~/.mydot/nvim/rc/deol.vim'



# 




##############################################################################
# currently not using
##############################################################################

# [[plugins]]
# repo = 'zchee/deoplete-jedi'
# on_ft = 'python'

# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# hook_add = 'source ~/.mydot/nvim/rc/deoplete.vim'

# [[plugins]]
# repo = 'nathanaelkane/vim-indent-guides'
# on_i = 1 hook_add = 'source ~/.mydot/nvim/rc/indent-guides.vim'

# [[plugins]]
# repo = 'itchyny/lightline.vim'
# on_i = 1
# hook_add = 'source ~/.mydot/nvim/rc/lightline.vim'

# [[plugins]]
# repo = 'neovim/node-client'
# 
# [[plugins]]
# repo = 'neovim/neovim-ruby'

# # completion
# [[plugins]]
# repo = 'plytophogy/vim-virtualenv'
# on_i = 1
# on_ft = 'python'
# 
# [[plugins]]
# repo = 'reireias/vim-cheatsheet'
# on_i = 1
# hook_add = 'source ~/.mydot/nvim/rc/vim-cheatsheet.vim'
# 
# [[plugins]]
# repo = 'pgilad/vim-skeletons'
# hook_add = 'source ~/.mydot/nvim/rc/skelentons.vim'
#
# [[plugins]]
# repo = 'lervag/vimtex'
# hook_add = 'source ~/.mydot/nvim/rc/vimtex.vim'

