[[plugins]]
repo = 'dense-analysis/ale'
hook_add = 'source ~/.mydot/nvim/rc/ale.vim'

[[plugins]]
repo = 'tweekmonster/braceless.vim'  # folds classes and functions
hook_add = 'source ~/.mydot/nvim/rc/braceless.vim'

[[plugins]]
repo = 'donRaphaco/neotex'
on_ft = 'latex'
hook_add = 'source ~/.mydot/nvim/rc/neotex.vim'

[[plugins]]
repo = 'preservim/tagbar'
hook_add = 'source ~/.mydot/nvim/rc/tagbar.vim'

[[plugins]]
repo = 'SirVer/ultisnips'  # snippets
hook_add = 'source ~/.mydot/nvim/rc/ultisnips.vim'

[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = 'source ~/.mydot/nvim/rc/vim-closetag.vim'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = 'source ~/.mydot/nvim/rc/vim-fugitive.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'source ~/.mydot/nvim/rc/vim-gitgutter.vim'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
hook_add = 'source ~/.mydot/nvim/rc/vim-json.vim'

[[plugins]]
repo = 'osyo-manga/vim-over'  # replace strings by s/"hoge"/"fuga"/g
hook_add = 'source ~/.mydot/nvim/rc/vim-over.vim'

[[plugins]]
repo = 'honza/vim-snippets'  # used by coc-snipptes

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'


##############################################################################
# testing
##############################################################################

# hook_add = '''
#   let g:UltiSnipsSnippetDirectories=["~/.mydot/nvim/snippet"]
#   let g:UltiSnipsJumpForwardTrigger="<tab>"
#   let g:UltiSnipsJumpBackwardTrigger="<s-tab>"
#   let g:UltiSnipsEditSplit="vertical"
#   '''



# ##############################################################################
# # currently not using
# ##############################################################################

# [[plugins]]
# repo = 'famiu/nvim-reload'  # reload


# [[plugins]]
# repo = 'puremourning/vimspector'  # test running
# on_ft = ['python']
# build = "./install_gadget.py --enable-python --force-enable-node"
# hook_add = 'source ~/.mydot/nvim/rc/vimspector.vim'

# [[plugins]]
# repo = 'thinca/vim-quickrun'
# on_ft = 'python'
# hook_add = 'source ~/.mydot/nvim/rc/quickrun.vim'


# [[plugins]]
# repo = 'davidhalter/jedi-vim'
# on_i = 1
# on_ft = 'python'
# hook_add = 'source ~/.mydot/nvim/rc/jedi-vim.vim'

# [[plugins]]
# repo = 'nvie/vim-flake8'
# on_i = 1
# on_ft = 'python'
# hook_add = 'source ~/.mydot/nvim/rc/flake8.vim'

# [[plugins]]
# repo = 'scrooloose/syntastic'

# [[plugins]]
# repo = 'tweekmonster/braceless.vim'
# on_ft  = 'python'
# hook_add = 'source ~/.mydot/nvim/rc/braceless.vim'

# [[plugins]]
# repo = 'zchee/deoplete-jedi'
# on_i = 1
# on_ft = 'python'

# [[plugins]]
# repo = 'neoclide/coc.nvim'
# merged = 0
# rev = 'release'
# hook_add = 'source ~/.mydot/nvim/rc/braceless.vim'

# hook_source = 'call coil398#init#coc#hook_source()'

# [[plugins]]
# repo = 't9md/vim-choosewin'
# hook_add = 'source ~/.mydot/nvim/rc/choosewin.vim'
# 
# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'
# # on_event = 'IntertEnter'
# 
# [[plugins]]
# repo = 'Shougo/neosnippet.vim'
# # on_event = 'IntertEnter'
# hook_add = 'source ~/.mydot/nvim/rc/neosnippet.vim'

# [[plugins]]
# repo = 'previm/previm'
# hook_add = 'source ~/.mydot/nvim/rc/previm.vim'
