#!/usr/bin/env perl

$latex            = 'latex -synctex=1 -halt-on-error -output-directory=build';
$bibtex           = 'bibtex';
$biber            = 'biber  -u -U --output_safechars';
$dvipdf           = 'dvipdfmx %O -o %D %S';
$makeindex        = 'mendex %O -o %D %S';
$max_repeat       = 5;
$pdf_mode         = 3;
$pvc_view_file_via_temporary = 0;
