[[plugins]]
repo = 'davidhalter/jedi-vim'
on_i = 1
on_ft = 'python'
hook_add = 'source ~/.mydot/nvim/rc/deoplete.vim'

# [[plugins]]
# repo = 'nvie/vim-flake8'
# on_i = 1
# on_ft = 'python'
# hook_add = 'source ~/.mydot/nvim/rc/flake8.vim'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'tweekmonster/braceless.vim'
on_ft  = 'python'
hook_add = 'source ~/.mydot/nvim/rc/braceless.vim'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_i = 1
on_ft = 'python'
