[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_i = 1

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'source ~/.mydot/nvim/rc/deoplete.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'source ~/.mydot/nvim/rc/nerdtree.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'source ~/.mydot/nvim/rc/quickrun.vim'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'
hook_add = 'source ~/.mydot/nvim/rc/easymotion.vim'

[[plugins]]
repo = 'pgilad/vim-skeletons'
hook_add = 'source ~/.mydot/nvim/rc/skelentons.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
on_i = 1
hook_add = 'source ~/.mydot/nvim/rc/indent-guides.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'vim-airline/vim-airline'
on_i = 1
hook_add = 'source ~/.mydot/nvim/rc/airline.vim'

[[plugins]]
repo = 'lervag/vimtex'
hook_add = 'source ~/.mydot/nvim/rc/vimtex.vim'
